openapi: 3.0.0
info:
  title: Forum Backend
  description: >
    Backend for forum
  version: 1.0.0
servers:
  - url: 'https://forum.example.com'
tags:
  - name: drafts
    description: >
      Paths to create, read, publish, delete and update the draft
  - name: threads
    description: >
      Paths to read, update, delete and do other operations on draft
  - name: users
    description: >
      Paths to perform operation on user
paths:
  /drafts/new:
    post:
      summary: /drafts/new
      description: >
        Create a draft for a user
      parameters:
        - in: header
          name: 'Authorization'
          description: 'JWT token header for the user'
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjaGhhcG9saWExMCIsIl9pZCI6IjVlODYxNzg0ZTg1NDY2ZmJhYmQyNTc2OCIsImlhdCI6MTU4NTg0NjI0Mn0.vJ5pQfIUX8jGSodwiKhxI9pP5HLFiko7uHUSLWeXM2k'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                draft:
                  type: object
                  description: draft object
                  properties:
                    content:
                      type: string
                      description: Content of the draft in markdown
                    title:
                      type: string
                      description: Title of the draft in markdown
                    tags:
                      type: array<string>
                      description: Tags for a forum thread
                      example:
                        ['google','forum']
      tags:
        - drafts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: true for sucess or false for faliure
                  draftId:
                    type: string
                    description: hexstring for draftId which was created
                    example: '5e86e1b20b805a00c91f0966'
        '403':
          description: not authorized
        '501':
          description: Server error
        '400':
          description: unknown error

  /drafts/all:
    get:
      summary: '/drafts/all'
      description: >

      parameters:
        - in: header
          name: 'Authorization'
          description: 'JWT token header for the user'
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjaGhhcG9saWExMCIsIl9pZCI6IjVlODYxNzg0ZTg1NDY2ZmJhYmQyNTc2OCIsImlhdCI6MTU4NTg0NjI0Mn0.vJ5pQfIUX8jGSodwiKhxI9pP5HLFiko7uHUSLWeXM2k'
      tags:
        - drafts
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  drafts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Draft'
        '403':
          description: not authorized
        '501':
          description: Server error
        '400':
          description: unknown error

  /drafts/one:
    get:
      summary: '/drafts/one'
      description: >

      parameters:
        - in: header
          name: 'Authorization'
          description: 'JWT token header for the user'
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjaGhhcG9saWExMCIsIl9pZCI6IjVlODYxNzg0ZTg1NDY2ZmJhYmQyNTc2OCIsImlhdCI6MTU4NTg0NjI0Mn0.vJ5pQfIUX8jGSodwiKhxI9pP5HLFiko7uHUSLWeXM2k'
        - in: query
          name: 'draftId'
          description: 'draft id hexstring'
          example: '5e86e1b20b805a00c91f0966'
      tags:
        - drafts
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  draft:
                    $ref: '#/components/schemas/Draft'
        '403':
          description: not authorized
        '501':
          description: Server error
        '400':
          description: unknown error

  /drafts/publish:
    post:
      summary: /drafts/publish
      description: >
        Publish a draft
      tags:
        - drafts
      parameters:
        - $ref: '#/components/parameters/JWT'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  threadId:
                    type: string
                    description: id of the thread
                  draftId:
                    type: string
                    description: id of the draft
        '500':
          description: Server error

  /drafts/delete:
    post:
      description: Delete a draft
      summary: /drafts/delete
      tags:
        - drafts
      parameters:
        - $ref: '#/components/parameters/JWT'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                draftId:
                  type: string
                  description: hexstring for draft
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  draftId:
                    type: string
                    description: hexstring for draft
        '500':
          $ref: '#/components/responses/SeverError'

  /drafts/update:
    post:
      description: Update fields of a draft
      summary: /drafts/update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                draft:
                  type: object
                  properties:
                    _id:
                      type: string
                      required: true
                      description: hexstring for the draft Id
                    content:
                      type: string
                      required: false
                    title:
                      type: string
                      required: false
                    tags:
                      type: array
                      items:
                        type: string
                      required: false
      tags:
        - drafts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  draftId:
                    type: string
                    description: id for the draft that was edited

  /thread/one:
    get:
      description: Read one thread
      summary: /thread/one

      responses:
        '200':


components:
  parameters:
    JWT:
      in: header
      name: 'Authorization'
      description: 'JWT token header for the user'
      example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjaGhhcG9saWExMCIsIl9pZCI6IjVlODYxNzg0ZTg1NDY2ZmJhYmQyNTc2OCIsImlhdCI6MTU4NTg0NjI0Mn0.vJ5pQfIUX8jGSodwiKhxI9pP5HLFiko7uHUSLWeXM2k'

  responses:
    'SeverError':
      description: server error

  schemas:
    Draft:
      type: object
      properties:
        title:
          type: string
          description: Title for the draft
          example:
            title content
        content:
          type: string
          description: Content for the draft
          example:
            draft content
        _id:
          type: string
          description: Draft's hexstring
          example: '5e86e1b20b805a00c91f0966'
        tags:
          type: array
          items:
            type: string
          description: Tags for a draft
          example:
            [google,tags]
