# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        mongodb-version: [4.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm ci
      - run: npm install codecov
      - run: npm run coverage
      - run: npm run codecov

      - name: Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.lcov

    env:
      CI: true
